---
- name: Ping localhost
  hosts: all
  gather_facts: yes

  vars:
    _target_env: |-
      {%- if survey_target_env is defined -%}
        {{ survey_target_env }}
      {%- elif aap_environment == 'dev' -%}
        {{ 'dev' }}
      {%- else -%}
        {{ aap_environment }}
      {%- endif -%}

  roles:
  - name: ansible_role_ping_{{ git_repo_branch | default('dev') }}

  tasks:
  - name: Just ping
    ping:

  - name: Show current greeting
    debug:
      msg: "greeting: {{ greeting | default('greeting is undefined') }} "
   
  - name: Set a custom fact
    set_fact:
      cacheable: yes
      foo: bar
      greeting: "{{ new_greeting | default('') }}"
      another: one

  - name: Show new greeting
    debug:
      msg: "greeting: {{ greeting }}"
      
  - name: Show greeting from hostvars
    debug:
      msg: "New Greeting #8: {{ hostvars[inventory_hostname]['greeting'] }}"

  - name: Wait
    pause:
      seconds: "{{ wait_time | default(0) }}"

  - name: DEBUG DEUBG
    debug:
      var: _target_env
