---
- name: Ping localhost
  hosts: all
  gather_facts: yes

  tasks:
  - name: Just ping
    ping:

  - name: Show old facts
    debug:
      msg: "greeting: {{ greeting | default('greeting is undefined') }} "
   
  - name: Set a custom fact
    set_fact:
      cacheable: yes
      foo: bar
      greeting: "{{ new_greeting | default('') }}"
      another: one
