---
- hosts: all
  gather_facts: no
  serial: "{{ serial_number | default(100) }}"

  tasks:
  - debug:
      msg: hello world

  - name: simulate big data
    community.general.read_csv:
      path: nyc_demographic_statistics_by_zip_code.csv
    delegate_to: localhost
    register: nyc

  - name: Find zip
    debug:
      msg: "{{ hostvars[inventory_hostname]['nyc']['list'] | map(attribute='JURISDICTION NAME') | join(',') }}"
#    when:
#    - "hostvars[inventory_hostname]['nyc']['JURISDICTION NAME'] == '11364'"

  - name: Wait
    pause:
      minutes: "{{ wait_time | default(2) }}"
