---
- name: Hello Test
  hosts: localhost

  sources:
    - ansible.eda.range:
        limit: 5

  rules:
    - name: Say Hello 1
      condition: event.i == 1
      action:
        run_playbook:
          name: ansible.eda.hello
    
    - name: Say Hello 2
      condition: event.i == 2
      action:
        run_playbook:
          name: ansible.eda.hello
