---
- name: Generic new poll for new records in ServiceNow
  hosts: all
  sources:
    - name: Watch for any updated table
      servicenow.itsm.records:
        table: incident
        interval: 5

  rules:
    - name: New incident
      condition: event.sys_id is defined
      actions:
        - print_event:
            pretty: true

