---
- name: Listen for events on a webhook
  hosts: web
  ## Define our source for events
  sources:
     - ansible.eda.url_check:
        urls:
          - http://ryzen5.lab.automate.nyc:8888/eda-demo/
        delay: 10

  rules:
    ## Define the conditions we are looking for 
    - name: Web site is up
      condition: event.url_check.status == "up"
      organization: ABC
      action:
        run_job_template:
          name: eda-demo

    - name: Web site is down
      condition: event.url_check.status == "down"
      organization: ABC
      action:
        run_job_template:
          name: eda-demo
