---
- name: Listen for webhook events
  hosts: all
 
  sources:
    - name: My webhook source
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 12345
 
  rules:
    - name: Webhook event with a message
      condition:
        all:
          - event.payload.message != ""
      action:
        run_job_template:
          name: "Ping"
          organization: ABC
          job_args:
            event_payload: "{{ event.payload }}"
