---
- name: Listen for webhook events
  hosts: all
 
  sources:
    - name: My webhook source
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 12345
    - name: My range
      ansible.eda.range:
        limit: 5
 
  rules:
    - name: Hello message
      condition:
        all:
          - event.payload.message == "hello" or event.payload.message == "Hello"
      action:
        debug:

    - name: Bye message
      condition:
        all:
          - event.payload.message == "bye"
      action:
        debug:
