---
plugin: servicenow.itsm.now
table: cmdb_ci_server
strict: false
instance:
  timeout: 1200
use_vars_plugins: true

#sysparm_query: nameSTARTSWITHnode
#sysparm_limit: 5

columns:
  - name
  - fqdn
  - os
  - os_version
  - serial_number
  - ip_address
  - asset.install_status
  - support_group.name
  - location.name

compose:
  ansible_host: fqdn
  composed_short_name: name.split('.')[0].split('_RETIRED')[0].split('_retired')[0].split('_Retired')[0]|lower

keyed_groups:
#  - key: os | regex_replace('\W|\/','_')
  - key: os
    prefix: CMDB_Keyed_Group_os
    parent_group: CMDB_Keyed_Group_os_ALL
    default_value: empty_cmdb_value

  - key: lookup('ansible.builtin.vars', 'asset.install_status')
    prefix: CMDB_Keyed_Group_{{ asset.install_status }}
    parent_group: CMDB_Keyed_Group_{{ asset.install_status }}_ALL
    default_value: empty_cmdb_value

  - key: lookup('ansible.builtin.vars', 'location.name')
    prefix: CMDB_Keyed_Group_{{ location.name }}
    parent_group: CMDB_Keyed_Group_{{ location.name }}_ALL
    default_value: empty_cmdb_value

groups:
  CMDB_Group_OS_ALL_RHEL: >- 
    "red hat" in os | lower
  CMDB_Group_OS_ALL_RHEL6: >- 
    "red hat" in os | lower and 
    "6." in os_version
  CMDB_Group_OS_ALL_RHEL7: >- 
    "red hat" in os | lower and 
    "7." in os_version
  CMDB_Group_OS_ALL_RHEL8: >- 
    "red hat" in os | lower and 
    "8." in os_version
  CMDB_Group_OS_ALL_RHEL9: >- 
    "red hat" in os | lower and 
    "9." in os_version
  CMDB_Group_OS_ALL_RHEL_DEV_SIT0_SIT_BAT: >-
    "red hat" in os | lower and
    u_os_environment in ["dev", "sit0", "sit", "bat"] | lower
... 
