---
- name: Azure Test
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Get all VMs info
      azure.azcollection.azure_rm_virtualmachine_info:
        auth_source: auto
        resource_group: "{{ resource_group | default(omit) }}"
        name: "{{ vm_name | default(omit) }}"

