---
- name: No-op template for EDA testing
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Display EDA event
      debug:
        var: ansible_eda

    - name: Set artifact
      set_stats:
        data:
          myvar: "{{ ansible_date_time.iso8601 }}"
          status: "{{ ansible_eda.event.body.status | default('failed') }}"
        per_host: false
