---
- name: Just ping
  hosts: all
  gather_facts: false

  tasks:
    - name: Task 1
      debug:
        var: foo

    - name: Task 2
      ping:

    - name: Task 3
      setup:

    - name: Task 4
      ping:
